import { Product, CustomProject, Photo } from '@/lib/types';

// Sample Products - will be replaced with database queries
export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Premium Teak Sofa',
    code: 'SOFA-001',
    category: 'seating',
    subcategory: 'sofas',
    usageType: 'Residential',
    price: 45000,
    stock: 5,
    dimensions: { height: 90, width: 220, length: 100 },
    woodType: 'Teak',
    finishType: 'Varnished',
    shortDesc: 'Luxurious 3-seater teak sofa with deep cushioning',
    longDesc: 'Crafted from premium teak wood, this sofa combines elegance with comfort. Features high-quality fabric upholstery and ergonomic design.',
    images: [
      {
        id: '1-1',
        imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500',
        imageType: 'front',
        displayOrder: 1,
      },
      {
        id: '1-2',
        imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500',
        imageType: 'lifestyle',
        displayOrder: 2,
      },
    ],
    reviews: [
      {
        id: 'r-1',
        productId: '1',
        userName: 'Rahul S.',
        rating: 5,
        comment: 'Excellent quality and craftsmanship! Highly satisfied.',
        createdAt: new Date('2024-02-15'),
      },
    ],
    has360View: true,
    hasVideo: false,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '2',
    name: 'Sheesham Dining Table',
    code: 'TABLE-001',
    category: 'tables',
    subcategory: 'dining-tables',
    usageType: 'Residential',
    price: 28000,
    stock: 8,
    dimensions: { height: 76, width: 180, length: 90 },
    woodType: 'Sheesham',
    finishType: 'Stained - Dark',
    shortDesc: '6-seater dining table with natural wood grain',
    longDesc: 'Beautiful sheesham wood dining table perfect for family gatherings. Features intricate detailing and exceptional durability.',
    images: [
      {
        id: '2-1',
        imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=500',
        imageType: 'front',
        displayOrder: 1,
      },
    ],
    reviews: [],
    has360View: false,
    hasVideo: false,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '3',
    name: 'Mango Wood Cabinet',
    code: 'CAB-001',
    category: 'storage',
    subcategory: 'cabinets',
    usageType: 'Residential',
    price: 18000,
    stock: 3,
    dimensions: { height: 150, width: 120, length: 45 },
    woodType: 'Mango Wood',
    finishType: 'Natural',
    shortDesc: 'Spacious storage cabinet with traditional design',
    longDesc: 'Handcrafted mango wood cabinet offering ample storage with beautiful aesthetic appeal. Perfect for living rooms.',
    images: [
      {
        id: '3-1',
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
        imageType: 'front',
        displayOrder: 1,
      },
    ],
    reviews: [],
    has360View: false,
    hasVideo: false,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '4',
    name: 'Teak Office Chair',
    code: 'CHAIR-001',
    category: 'office',
    subcategory: 'office-chairs',
    usageType: 'Commercial',
    price: 12000,
    stock: 12,
    dimensions: { height: 100, width: 65, length: 65 },
    woodType: 'Teak',
    finishType: 'Varnished',
    shortDesc: 'Ergonomic office chair with teak wood frame',
    longDesc: 'Professional office chair combining style and comfort. Features adjustable height and 360-degree rotation.',
    images: [
      {
        id: '4-1',
        imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=500',
        imageType: 'front',
        displayOrder: 1,
      },
    ],
    reviews: [],
    has360View: false,
    hasVideo: false,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '5',
    name: 'Garden Patio Set',
    code: 'PATIO-001',
    category: 'outdoor',
    subcategory: 'patio-sets',
    usageType: 'Outdoor',
    price: 35000,
    stock: 4,
    dimensions: { height: 75, width: 150, length: 80 },
    woodType: 'Teak',
    finishType: 'Varnished',
    shortDesc: 'Weather-resistant outdoor patio furniture set',
    longDesc: 'Premium outdoor set crafted from treated teak, ideal for gardens and patios. Includes table and 4 chairs.',
    images: [
      {
        id: '5-1',
        imageUrl: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=500',
        imageType: 'front',
        displayOrder: 1,
      },
    ],
    reviews: [],
    has360View: false,
    hasVideo: false,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '6',
    name: 'Walnut Queen Bed',
    code: 'BED-001',
    category: 'sleeping',
    subcategory: 'beds',
    usageType: 'Residential',
    price: 55000,
    stock: 2,
    dimensions: { height: 120, width: 160, length: 210 },
    woodType: 'Walnut',
    finishType: 'Varnished',
    shortDesc: 'Luxury queen-size bed with walnut wood frame',
    longDesc: 'Elegant queen bed crafted from premium walnut wood. Features a solid construction and timeless design.',
    images: [
      {
        id: '6-1',
        imageUrl: 'https://images.unsplash.com/photo-1540932239986-310128078ceb?w=500',
        imageType: 'front',
        displayOrder: 1,
      },
    ],
    reviews: [],
    has360View: true,
    hasVideo: false,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-03-01'),
  },
];

// Sample Custom Projects for showcasing
export const SAMPLE_CUSTOM_PROJECTS: CustomProject[] = [
  {
    id: 'cp-1',
    title: 'Modern Living Room Transformation',
    description: 'Complete living room furniture set customized for a contemporary home',
    beforeImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500',
    afterImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500',
    category: 'Living Room',
  },
  {
    id: 'cp-2',
    title: 'Custom Office Workspace',
    description: 'Bespoke office furniture design for corporate space',
    beforeImage: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=500',
    afterImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=500',
    category: 'Office',
  },
  {
    id: 'cp-3',
    title: 'Luxury Bedroom Suite',
    description: 'Complete bedroom furniture set with custom dimensions',
    beforeImage: 'https://images.unsplash.com/photo-1564078369132-52d829e42d19?w=500',
    afterImage: 'https://images.unsplash.com/photo-1540932239986-310128078ceb?w=500',
    category: 'Bedroom',
  },
];

// Featured Categories for home page
export const FEATURED_CATEGORIES = [
  {
    id: 'seating',
    name: 'Seating Solutions',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500',
    description: 'Comfortable and stylish seating for any space',
  },
  {
    id: 'dining',
    name: 'Dining Furniture',
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=500',
    description: 'Elegant dining solutions for family gatherings',
  },
  {
    id: 'sleeping',
    name: 'Bedroom Collection',
    image: 'https://images.unsplash.com/photo-1540932239986-310128078ceb?w=500',
    description: 'Premium beds and sleeping furniture',
  },
  {
    id: 'storage',
    name: 'Storage & Organization',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    description: 'Functional and beautiful storage solutions',
  },
];

// Photos for home page gallery
export const photos: Photo[] = [
  {
    id: 'photo-1',
    title: 'Artisan Craftsmanship',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    category: 'Furniture',
    description: 'Handcrafted furniture pieces',
  },
  {
    id: 'photo-2',
    title: 'Modern Living Room',
    imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
    category: 'Interior',
    description: 'Contemporary living spaces',
  },
  {
    id: 'photo-3',
    title: 'Luxury Bedroom',
    imageUrl: 'https://images.unsplash.com/photo-1540932239986-310128078ceb?w=800',
    category: 'Bedroom',
    description: 'Elegant bedroom designs',
  },
  {
    id: 'photo-4',
    title: 'Custom Cabinetry',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    category: 'Storage',
    description: 'Bespoke storage solutions',
  },
  {
    id: 'photo-5',
    title: 'Designer Seating',
    imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800',
    category: 'Seating',
    description: 'Premium seating options',
  },
  {
    id: 'photo-6',
    title: 'Outdoor Living',
    imageUrl: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800',
    category: 'Outdoor',
    description: 'Outdoor furniture collections',
  },
  {
    id: 'photo-7',
    title: 'Workspace Solutions',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    category: 'Office',
    description: 'Professional office furniture',
  },
  {
    id: 'photo-8',
    title: 'Dining Excellence',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    category: 'Dining',
    description: 'Fine dining furniture',
  },
];
